Playlist Generator/Playlist Generator/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Playlist_Generator.Models;
using PlaylistGenerator.Services.Contracts;
using PlaylistGenerator.Services.DTOs;

namespace Playlist_Generator.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILoginService service;
        private readonly IMapper mapper;

        public LoginController(ILoginService service, IMapper mapper)
        {
            this.service = service;
            this.mapper = mapper;
        }

        // GET Login/Index
        public IActionResult Index()
        {
            return View();
        }

        // POST Login/Index
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(LoginViewModel model)
        {
            if(ModelState.IsValid)
            {
                var userDTO = this.mapper.Map<UserDTO>(model);
                var result = await this.service.LoginUserAsync(userDTO);

                if(result == true)
                {
                    return RedirectToAction(nameof(Index), "Home");
                }

            }
                return View(model);
        }
    }
}

Playlist Generator/Playlist Generator/Controllers/LogoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using PlaylistGenerator.Services.Contracts;

namespace Playlist_Generator.Controllers
{
    public class LogoutController : Controller
    {
        private readonly ILoginService service;

        public LogoutController(ILoginService service)
        {
            this.service = service;
        }

        // GET logout/index
        public IActionResult Index()
        {
            this.service.LogoutUserAsync();

            return RedirectToAction("Index", "Home");
        }
    }
}

Playlist Generator/Playlist Generator/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Playlist_Generator.Models;
using PlaylistGenerator.Data.Models;
using PlaylistGenerator.Services.Contracts;
using PlaylistGenerator.Services.DTOs;

namespace Playlist_Generator.Controllers
{
    public class MapController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IPlaylistService playlistService;

        public MapController(UserManager<User> userManager, IPlaylistService playlistService)
        {
            this.userManager = userManager;
            this.playlistService = playlistService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "User, Admin")]
        public async Task<IActionResult> GeneratePlaylist()
        {
            await Task.Delay(0);

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "User, Admin")]
        public async Task<IActionResult> GeneratePlaylist(GeneratePlaylistViewModel generatePlaylistViewModel)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }

            bool sameArtist = generatePlaylistViewModel.AllowDuplicateArtists;
            bool topRanked = generatePlaylistViewModel.TopRatedTracks;
            string title = generatePlaylistViewModel.Title;
            var user = await this.userManager.GetUserAsync(User);

            Dictionary<Genres, double> genrePercetages = new Dictionary<Genres, double>();

            genrePercetages.Add(generatePlaylistViewModel.FirstGenre, generatePlaylistViewModel.FirstGenrePercentage);
            if(generatePlaylistViewModel.FirstGenre != generatePlaylistViewModel.SecondGenre)
                genrePercetages.Add(generatePlaylistViewModel.SecondGenre, generatePlaylistViewModel.SecondGenrePercentage);
            
            HttpClient client = new HttpClient();
            var url = $"https://dev.virtualearth.net/REST/v1/Routes/DistanceMatrix?origins={generatePlaylistViewModel.BingDestinationsViewModel.FirstDestinationLat},{generatePlaylistViewModel.BingDestinationsViewModel.FirstDestinationLon}&destinations={generatePlaylistViewModel.BingDestinationsViewModel.SecondDestinationLat},{generatePlaylistViewModel.BingDestinationsViewModel.SecondDestinationLon}&travelMode=driving&key=Ag1-oHlx6OC_A4B6GFHeLGTcOZ8hYGIr-ifRsFRjGkFgXE3nLPe_jU1dXYy_MDk7";
            var response = await client.GetStringAsync(url);
            var jsonObject = JsonConvert.DeserializeObject<JsonBingResponse>(response);
            var duration = jsonObject.ResourceSets[0].Resources[0].Results[0].TravelDuration;

            var playlistDTO = await this.playlistService.GeneratePlaylistAsync((int)duration, sameArtist, topRanked, genrePercetages, user, title);


            return RedirectToAction("DetailsAfterGeneration", "Playlist", playlistDTO);
        }
    }
}

Playlist Generator/Playlist Generator/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Playlist_Generator.Models;
using PlaylistGenerator.Services.Contracts;
using PlaylistGenerator.Services.DTOs;

namespace Playlist_Generator.Controllers
{
    public class RegisterController : Controller
    {
        private readonly IRegisterService service;
        private readonly IMapper mapper;

        public RegisterController(IRegisterService service, IMapper mapper)
        {
            this.service = service;
            this.mapper = mapper;
        }

        // GET: Register/Index
        public IActionResult Index()
        {
            return View();
        }

        // POST: Register/Index 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(RegisterViewModel model)
        {

            if (ModelState.IsValid)
            {
                var userDTO = mapper.Map<UserDTO>(model);
                bool result = await service.RegisterUserAsync(userDTO);

                if (result == true)
                    return RedirectToAction(nameof(Index), "Home");
            }

            return View(model);
        }

    }
}

Playlist Generator/Playlist Generator/Views/Shared/_Layout.cshtml
@inject SignInManager<User> signInManager
@inject UserManager<User> userManager

@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Playlist_Generator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/css/animate.min.css" rel="stylesheet" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/jquery-ui.css" rel="stylesheet" />
    <link href="~/css/jquery.mCustomScrollbar.min.css" rel="stylesheet" />
    <link href="~/css/meanmenu.css" rel="stylesheet" />
    <link href="~/css/nice-select.css" rel="stylesheet" />
    <link href="~/css/normalize.css" rel="stylesheet" />
    <link href="~/css/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/css/responsive.css" rel="stylesheet" />
    <link href="~/css/slick.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div class="header">
            <div class="container">
                <div class="row">
                    <div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col logo_section">
                        <div class="full">
                            <div class="center-desk">
                                <div class="logo">
                                    <a asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/logo2.jpg" alt="logo"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-10 col-lg-8 col-md-10 col-sm-10">
                        <div class="menu-area">
                            <div class="limit-box">
                                <nav class="main-menu" style="display: block;">
                                    <ul class="menu-area-main">
                                        <li class="">
                                            <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                        </li>
                                        @if (signInManager.IsSignedIn(User))
                                        {
                                            @if (User.Identity.IsAuthenticated)//@if (User.IsInRole("User"))
                                            {
                                                <li class="">
                                                    <a asp-area="" asp-controller="Map" asp-action="GeneratePlaylist">Generate Playlist</a>
                                                </li>
                                                <li class="">
                                                    <a asp-area="" asp-controller="Playlist" asp-action="Index">All Playlists</a>
                                                </li>
                                                <li class="dropdown hoverable">
                                                    <a asp-controller="Home"
                                                       class="nav-link " data-toggle="dropdown">Hello, @User.Identity.Name!<b class="caret"></b></a>
                                                </li>
                                            }
                                            @if (User.IsInRole("Admin"))
                                            {
                                                <li class="hoverable">
                                                    <a class="nav-link " id="register" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                                                </li>
                                            }
                                            <li class="hoverable">
                                                <a id="logout" class="nav-link" asp-controller="Logout" asp-action="Index">Logout</a>
                                            </li>
                                        }

                                        else
                                        {
                                            <li class="hoverable">
                                                <a class="nav-link " id="register" asp-controller="Register" asp-action="Index">Register</a>
                                            </li>
                                            <li class="hoverable">
                                                <a class="nav-link " id="login" asp-controller="Login" asp-action="Index">Login</a>
                                            </li>
                                        }
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end header inner -->
        </div>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Playlist_Generator</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav">
                            @if (signInManager.IsSignedIn(User))
                            {

                                @if (User.IsInRole("Admin"))
                                {
                                    <li class="hoverable">
                                        <a class="nav-link " id="register" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                                    </li>
                                }

                                @if (User.Identity.IsAuthenticated)//@if (User.IsInRole("User"))
                                {
                                    <li class="dropdown hoverable">
                                        <a asp-controller="Home"
                                           class="nav-link " data-toggle="dropdown">Hello, @User.Identity.Name!<b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a class="nav-link text-dark" asp-controller="UserMenu" asp-action="MyStatus">My Status</a>
                                            </li>
                                        </ul>
                                    </li>
                                }

                                <li class="hoverable">
                                    <a id="logout" class="nav-link" asp-controller="Logout" asp-action="Index">Logout</a>
                                </li>
                            }

                            else
                            {
                                <li class="hoverable">
                                    <a class="nav-link " id="register" asp-controller="Register" asp-action="Index">Register</a>
                                </li>
                                <li class="hoverable">
                                    <a class="nav-link " id="login" asp-controller="Login" asp-action="Index">Login</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>*@
    </header>
    <main role="main">
        @RenderBody()
    </main>
    
    <footer class="">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery.validate.js"></script>
    <script src="~/js/plugin.js"></script>
    <script src="~/js/popper.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>