Playlist Generator/Playlist Generator/Models/PlaylistViewModel.cs
using PlaylistGenerator.Services.DTOs;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace Playlist_Generator.Models
{
    public class PlaylistViewModel
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string URL { get; set; }
        public string Genres { get; set; }
        [DisplayName("Time")]
        public int TotalPlayTime { get; set; }
        [DisplayName("Rank")]
        public double AvrRank { get; set; }
        
        public IEnumerable<SongDTO> Songs { get; set; }
    }
}

Playlist Generator/Playlist Generator/Models/PlaylistsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PlaylistGenerator.Services.DTOs;

namespace Playlist_Generator.Models
{
    public class PlaylistsViewModel
    {
        public IEnumerable<PlaylistDTO> Playlists { get; set; }

    }
}

Playlist Generator/Playlist Generator/Controllers/PlaylistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Playlist_Generator.Models;
using PlaylistGenerator.Services.Contracts;
using PlaylistGenerator.Services.DTOs;

namespace Playlist_Generator.Controllers
{
    public class PlaylistController : Controller
    {
        private readonly IPlaylistService playlistService;
        private readonly IMapper mapper;

        public PlaylistController(IPlaylistService playlistService, IMapper mapper)
        {
            this.playlistService = playlistService;
            this.mapper = mapper;
        }

        // GET: PlaylistController
        public ActionResult Index()
        {
            var playlists = this.playlistService.GetAllPlaylists();

            PlaylistsViewModel model = new PlaylistsViewModel()
            { Playlists = playlists };

            return View(model);
        }

        // GET: PlaylistController/Details/5
        [Authorize(Roles = "User, Admin")]
        public async Task<ActionResult> Details(Guid id)
        {
            var playlist = await this.playlistService.GetPlaylist(id);

            var model = this.mapper.Map<PlaylistViewModel>(playlist);

            return View(model);
        }

        [Authorize(Roles = "User, Admin")]
        public ActionResult DetailsAfterGeneration(PlaylistDTO playlistDTO)
        {
            var model = this.mapper.Map<PlaylistViewModel>(playlistDTO);

            return View(nameof(Details), model);
        }


        // GET: PlaylistController/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(Guid id)
        {
            var playlist = await this.playlistService.GetPlaylist(id);

            return View(playlist);
        }

        // POST: PlaylistController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(PlaylistDTO playlist)
        {
            await this.playlistService.EditPlaylist(playlist);

            return RedirectToAction(nameof(Index));
        }

        // GET: PlaylistController/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(Guid id)
        {
            var playlist = await this.playlistService.GetPlaylist(id);

            if(playlist == null)
            {
                return NotFound();
            }

            return View(playlist);
        }

        // POST: PlaylistController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(PlaylistDTO playlistDTO)
        {
            var result = await this.playlistService.DeletePlaylist(playlistDTO.Id);

            if(result)
            {
                return RedirectToAction(nameof(Index));
            }

            return NotFound();
        }

        [Authorize(Roles = "User, Admin")]
        public async Task<ActionResult> Songs(Guid id)
        {
            var playlist = await this.playlistService.GetPlaylist(id);

            var model = this.mapper.Map<PlaylistViewModel>(playlist);

            model.Songs = this.playlistService.GetPlaylistsSongs(id);

            if (model.Songs == null)
            {
                return NotFound();
            }

            return View(model);
        }

    }
}

Playlist Generator/Playlist Generator/Controllers/SongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlaylistGenerator.Services.Contracts;

namespace Playlist_Generator.Controllers
{
    public class SongController : Controller
    {
        private readonly ISongService service;
        private readonly IMapper mapper;

        public SongController(ISongService service, IMapper mapper)
        {
            this.service = service;
            this.mapper = mapper;
        }

        [Authorize(Roles = "User, Admin")]
        public async Task<IActionResult> Details(Guid id)
        {
            var song = await this.service.GetSong(id);

            return View(song);
        }
    }
}

Playlist Generator/Playlist Generator/Views/Playlist/Delete.cshtml
@model PlaylistDTO

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style>
    body {
        background-image: url('../../../images/deletebackground.jpg');
    }
</style>
<div class="container">
    <div class="my-3">
        <h1>Are you sure you want to delete this playlist?</h1>
    </div>
    <div>
        <dl class="row">
            <dt class="col-sm-2 my-4">
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd class="col-sm-10 my-4">
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Genres)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Genres)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.TotalPlayTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TotalPlayTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.AvrRank)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AvrRank)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger text-white" />
            <a asp-action="Index" class="btn bg-dark mx-2">Back to List</a>
        </form>
    </div>
</div>
</div>

Playlist Generator/Playlist Generator/Views/Playlist/Details.cshtml
@model PlaylistViewModel
@inject UserManager<User> userManager
@inject SignInManager<User> signInManager

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    body {
        background-image: url('../../../images/detailsbackground.jpg');
    }
</style>

<div class="container">
    <div class="col-md-3 my-3">
        <h1>Playlist details</h1>
        <dl class="row">
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.Genres)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Genres)
            </dd>
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.TotalPlayTime)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.TotalPlayTime)
            </dd>
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.AvrRank)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.AvrRank)
            </dd>
        </dl>
    </div>
    <div>

        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
        {
            <button class="btn bg-dark mx-2">
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "text-green" })
            </button>
        }
        <button class="btn bg-dark">
            <a asp-action="Index">Back to List</a>
            <button class="btn bg-success mx-2 text-white">
                <a asp-action="Songs" asp-route-id="@Model.Id">View all songs</a>
            </button>
        </button>
    </div>
</div>

Playlist Generator/Playlist Generator/Views/Playlist/Edit.cshtml
@model PlaylistDTO

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style>
    body {
        background-image: url('../../../images/editbackground.jpg');
    }
</style>

<div class="container">
    <h1 class="pt-2">Edit playlist title</h1>
    <div class="row" style="margin-top: 30px" ;>
        <div class="col-md-3">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-success text-white" />
                    <a class="btn bg-dark mx-2" asp-action="Index">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>

Playlist Generator/Playlist Generator/Views/Playlist/Index.cshtml
@model PlaylistsViewModel
@inject UserManager<User> userManager
@inject SignInManager<User> signInManager

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/css/datatable.css" rel="stylesheet" />
<div style="background-image: url('../../../images/background3.jpg')">
    <div class="container py-4">
        <table id="table_id">
            <h1 class="mb-3">All playlists</h1>
            <thead>
                <tr>
                    <th style="width: 35%">
                        @Html.DisplayNameFor(model => model.Playlists.First().Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Playlists.First().TotalPlayTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Playlists.First().AvrRank)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var playlist in Model.Playlists)
                {
                    <tr style="background: rgba(0, 0, 0, 0.7)">
                        <td style="width: 35%">
                            @Html.DisplayFor(modelItem => playlist.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => playlist.TotalPlayTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => playlist.AvrRank)
                        </td>
                        <td>
                            <div style="text-align: right">
                                @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                                {

                                    <button class="btn bg-dark">
                                        @Html.ActionLink("Edit", "Edit", new { id = playlist.Id })
                                    </button>
                                    <button class="btn bg-dark">
                                        @Html.ActionLink("Delete", "Delete", new { id = playlist.Id })
                                    </button>
                                }
                                <button class="btn bg-dark mx-1">
                                    @Html.ActionLink("Details", "Details", new { id = playlist.Id })
                                </button>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>
<script>
    window.$('#table_id').DataTable();
</script>

Playlist Generator/Playlist Generator/Views/Playlist/Songs.cshtml
@model PlaylistViewModel

@{
    ViewData["Title"] = "Users";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<link href="~/css/datatable.css" rel="stylesheet" />
<div style="background-image: url('../../../images/background4.jpg')">
    <div class="container py-3">
        <table id="table_id">
            <thead>
                <h1 class="mb-1">@Model.Title</h1>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Songs.First().Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Songs.First().Duration)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Songs.First().Genre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Songs.First().Rank)
                    </th>
                    <th style="width: 95px">
                        Details
                    </th>
                    <th style="width: 50px">
                        Preview
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var song in Model.Songs)
                {
                    var url = song.Url;
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => song.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => song.Duration)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => song.Genre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => song.Rank)
                        </td>
                        <td>
                            <button class="btn bg-dark mx-2">
                                <a asp-controller="Song" asp-action="Details" asp-route-id="@song.Id">Details</a>
                            </button>
                        </td>
                        <td>
                            <a href="#!" onclick="playAudio(@Html.Raw("'" + song.Url + "'"))">
                                <div id="@song.Url play">
                                    <svg width="4em" height="4em" viewBox="0 0 16 16" class="bi bi-play" fill="currentColor" xmlns="http://www.w3.org/2000/svg%22%3E">
                                        <path fill-rule="evenodd" d="M10.804 8L5 4.633v6.734L10.804 8zm.792-.696a.802.802 0 0 1 0 1.392l-6.363 3.692C4.713 12.69 4 12.345 4 11.692V4.308c0-.653.713-.998 1.233-.696l6.363 3.692z" />
                                    </svg>
                                </div>
                                <div id="@song.Url pause" style="display: none">
                                    <svg width="4em" height="4em" viewBox="0 0 16 16" class="bi bi-pause" fill="currentColor" xmlns="http://www.w3.org/2000/svg%22%3E">
                                        <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-1 0V4a.5.5 0 0 1 .5-.5zm4 0a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-1 0V4a.5.5 0 0 1 .5-.5z" />
                                    </svg>
                                </div>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>
<script>
    window.$('#table_id').DataTable();
</script>
<script>
    var audio;
    function playAudio(value) {
        if (!value) {
            alert("Unfortunetely we could not find a preview for this song.")
            return
        }
        if (!audio) {
            audio = new Audio(value);
            audio.volume = 0.2;
            audio.onended = function () {
                playPause(audi.src);
            }
            audio.play();
            playPause(audio.src);
        }
        else if (audio.src !== value) {
            if (audio.paused === false) {
                audio.pause();
                playPause(audio.src);
            }
            audio = new Audio(value);
            audio.volume = 0.2;
            audio.onended = function () {
                playPause(audi.src);
            }
            audio.play();
            playPause(audio.src);
        }
        else if (audio.paused || audio.ended) {
            audio.play();
            playPause(audio.src);
        }
        else {
            audio.pause();
            playPause(audio.src);
        }
    }
    function playPause(url) {
        var divPlay = document.getElementById(url + " play");
        var pausePlay = document.getElementById(url + " pause");

        divPlay.style.display = divPlay.style.display === "none" ? "block" : "none"
        pausePlay.style.display = pausePlay.style.display === "none" ? "block" : "none"
    }
</script>